image: python:3.10

stages:
  - build
  - deploy

variables:
  GROUP_RUNNER_TAG: "nodejs"

sphinx:
  stage: build
  script:
  - apt-get update && apt-get install -y texlive-latex-base texlive-fonts-recommended texlive-fonts-extra texlive-latex-extra
  - pip install sphinx && pip install sphinx-rtd-theme
  - sphinx-build -b html . dist
  - make latexpdf
  - mv _build/latex/*.pdf dist/$CI_PROJECT_NAME.pdf
  artifacts:
    paths:
    - dist
  # rules:
  #   - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH
  only:
    - main
  tags:
    - $GROUP_RUNNER_TAG

pages:
  stage: deploy
  script:
    - rm -rf .public
    - mkdir -p .public
    - mv dist/* .public
    - rm -rf public
    - mv .public public
  artifacts:
    paths:
      - public
  only:
    - main
  tags:
    - $GROUP_RUNNER_TAG

