image: python:3.10-alpine

stages:
  - build
  - deploy

variables:
  GROUP_RUNNER_TAG: "nodejs"

build:
  stage: build
  script:
  - pip install -U sphinx
  - pip install -r requirements.txt
  - sphinx-build -b html . public
  rules:
    - if: $CI_COMMIT_REF_NAME != $CI_DEFAULT_BRANCH
  tags:
    - $GROUP_RUNNER_TAG
  
pages:
  stage: deploy
  script:
  - pip install -U sphinx
  - sphinx-build -b html . public
  artifacts:
    paths:
    - public
  rules:
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH
  tags:
    - $GROUP_RUNNER_TAG


